### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Kalimon12** [drsigned/sigurlx#3]
how use this tools
sigurlx
sigrawler
lazyhunter
need ex:

**Comment by drsigned** [comment]
Hey @Kalimon12 ,
**FYI:** I made the mentioned tools lately for personal use but I figured it bring no harm to make them public.
- sigrawler is a web crawl that currently extracts URLs and S3 buckets
- sigurlx is well IDK, but i use it to probe urls, like: categorize urls, probe for commonly vulnerable parameters (kinda like [parth](https://github.com/s0md3v/Parth) ), probe for reflected parameters, probe for DOMXSS, probe request for status_code, content_type, e.t.c
- lazyhunter is a script to automate currently part of my web recon workflow
